/**
 * PolyViz - Core Polynomial Mathematics (all implemented from scratch)
 *
 * This module contains PURE, DETERMINISTIC, CLASSICAL MATHEMATICS.
 * NO AI, NO LLMs, NO MACHINE LEARNING, NO EXTERNAL APIS, NO NETWORK CALLS.
 * Everything is ordinary hand-written JavaScript implementing standard algebra
 * and numerical methods that any student or textbook would use by hand.
 *
 * Techniques implemented locally:
 * - Horner's method for fast polynomial evaluation
 * - Exact symbolic derivative (coefficient arithmetic)
 * - Rational Root Theorem (possible rational roots p/q)
 * - Synthetic division with full visible table for teaching
 * - Completing the Square (manual algebraic steps for quadratics)
 * - Newton-Raphson numeric refinement + sign-change bracketing for higher degrees
 * - Honest Abel–Ruffini note for degree ≥ 5
 *
 * The "Step-by-Step" output is generated by deterministic string construction
 * that mirrors exactly what a human writes on paper. No symbolic solver or AI
 * is ever invoked.
 *
 * Coefficient convention (VERY IMPORTANT):
 *   coeffs[0] is the LEADING (highest degree) coefficient.
 *   coeffs[coeffs.length-1] is the constant term.
 *   Example: [2, -5, 0, 1]  ===  2x^3 - 5x^2 + 1
 *   Degree = coeffs.length - 1
 *
 * All functions are deterministic and educational-first. They run 100% in the
 * browser with zero external dependencies besides the JavaScript runtime.
 */

export type Coeffs = number[];

// ---------------------------------------------------------------------------
// Basic helpers
// ---------------------------------------------------------------------------

/** Remove leading zero coefficients while keeping at least one value. */
export function normalize(coeffs: Coeffs): Coeffs {
  if (!coeffs || coeffs.length === 0) return [0];
  let start = 0;
  while (start < coeffs.length - 1 && Math.abs(coeffs[start]) < 1e-12) {
    start++;
  }
  const result = coeffs.slice(start);
  // Guard against all-zero becoming empty
  return result.length === 0 ? [0] : result;
}

/** Safe degree (highest power with non-zero coeff). */
export function degree(coeffs: Coeffs): number {
  const n = normalize(coeffs);
  return n.length - 1;
}

/** Leading coefficient (0 for the zero polynomial). */
export function leading(coeffs: Coeffs): number {
  const n = normalize(coeffs);
  return n[0];
}

// ---------------------------------------------------------------------------
// Horner's method for fast & stable evaluation
// ---------------------------------------------------------------------------

/**
 * Evaluate p(x) using Horner's method (O(n) instead of naive O(n^2) powers).
 *
 * Horner's rule rewrites:
 *   a3 x^3 + a2 x^2 + a1 x + a0   ===   ((a3 * x + a2) * x + a1) * x + a0
 *
 * This reduces multiplications and is numerically more stable.
 */
export function evaluate(coeffs: Coeffs, x: number): number {
  const n = normalize(coeffs);
  if (n.length === 1) return n[0]; // constant
  let result = n[0];
  for (let i = 1; i < n.length; i++) {
    result = result * x + n[i];
  }
  return result;
}

// ---------------------------------------------------------------------------
// Derivative
// ---------------------------------------------------------------------------

/**
 * Compute the exact derivative coefficients.
 * If p(x) = a_n x^n + ... + a1 x + a0
 * Then p'(x) = n*a_n x^{n-1} + ... + a1
 */
export function derivative(coeffs: Coeffs): Coeffs {
  const n = normalize(coeffs);
  if (n.length <= 1) return [0];
  const d: number[] = [];
  const deg = n.length - 1;
  for (let i = 0; i < deg; i++) {
    d.push(n[i] * (deg - i));
  }
  return normalize(d);
}

// ---------------------------------------------------------------------------
// Pretty printing (critical for educational UI)
// ---------------------------------------------------------------------------

/** Format a number nicely for students: integers stay integers, small floats are cleaned. */
export function formatNumber(n: number, maxDecimals = 4): string {
  if (!isFinite(n)) return '∞';
  const rounded = Math.round(n * 1e10) / 1e10; // remove float noise
  if (Math.abs(rounded - Math.round(rounded)) < 1e-10) {
    return String(Math.round(rounded));
  }
  // Try to show as simple decimal without trailing zeros
  return rounded.toFixed(maxDecimals).replace(/\.?0+$/, '');
}

/** Turn coeffs back into a human string like "2x^3 - 5x^2 + 1". */
export function polyToString(coeffs: Coeffs, variable = 'x'): string {
  const n = normalize(coeffs);
  if (n.length === 1 && n[0] === 0) return '0';
  const terms: string[] = [];
  const deg = n.length - 1;

  for (let i = 0; i < n.length; i++) {
    const power = deg - i;
    const c = n[i];
    if (Math.abs(c) < 1e-12) continue;

    let term = '';
    const absC = Math.abs(c);
    const sign = c < 0 ? '-' : '+';

    if (power === 0) {
      term = formatNumber(absC);
    } else if (power === 1) {
      if (absC === 1) term = variable;
      else term = `${formatNumber(absC)}${variable}`;
    } else {
      if (absC === 1) term = `${variable}^${power}`;
      else term = `${formatNumber(absC)}${variable}^${power}`;
    }

    if (terms.length === 0) {
      // first term keeps its real sign
      terms.push(c < 0 ? '-' + term.replace(/^\+/, '') : term);
    } else {
      terms.push(`${sign} ${term}`);
    }
  }

  if (terms.length === 0) return '0';
  return terms.join(' ').replace(/^\+ /, '');
}

// ---------------------------------------------------------------------------
// Rational Root Theorem helpers
// ---------------------------------------------------------------------------

/** Return positive + negative divisors of n (used by Rational Root Theorem). */
export function getFactors(n: number): number[] {
  const absN = Math.max(1, Math.round(Math.abs(n)));
  const factors: number[] = [];
  for (let i = 1; i * i <= absN; i++) {
    if (absN % i === 0) {
      factors.push(i);
      if (i !== absN / i) factors.push(absN / i);
    }
  }
  // include negatives too (RRT cares about sign)
  const signed = [...factors, ...factors.map(f => -f)];
  return [...new Set(signed)].sort((a, b) => a - b);
}

/**
 * Rational Root Theorem:
 * Any rational root, expressed in lowest terms p/q, must have:
 *   p is a factor of the constant term
 *   q is a factor of the leading coefficient
 *
 * This dramatically reduces the candidates a student has to test.
 */
export function possibleRationalRoots(coeffs: Coeffs): number[] {
  const n = normalize(coeffs);
  if (n.length <= 1) return [];
  const lead = n[0];
  const cons = n[n.length - 1];
  if (Math.abs(cons) < 1e-12) {
    // 0 is a root when constant term = 0
    return [0, ...possibleRationalRoots(n.slice(0, -1))];
  }
  const p = getFactors(cons);
  const q = getFactors(lead);
  const candidates: number[] = [];
  for (const num of p) {
    for (const den of q) {
      candidates.push(num / den);
    }
  }
  // unique + sorted
  return [...new Set(candidates.map(c => Math.round(c * 1e9) / 1e9))].sort((a, b) => a - b);
}

// ---------------------------------------------------------------------------
// Synthetic Division (with full table for teaching)
// ---------------------------------------------------------------------------

export interface SyntheticResult {
  quotient: Coeffs;
  remainder: number;
  /** Rows useful for rendering an educational division table */
  table: {
    rootLabel: string;
    coeffsRow: number[];
    productsRow: number[];
    bottomRow: number[];
  };
}

/**
 * Perform synthetic division by a root candidate r.
 * Returns the quotient polynomial and remainder, plus data to display every step.
 *
 * Example for (x^3 - 6x^2 + 11x - 6) / (x - 1):
 *   1 | 1  -6  11  -6
 *       |     1   -5   6
 *       ----------------
 *         1  -5   6    0     <- quotient [1,-5,6], rem 0
 */
export function syntheticDivision(coeffs: Coeffs, root: number): SyntheticResult {
  const n = normalize(coeffs);
  if (n.length === 0) {
    return { quotient: [0], remainder: 0, table: { rootLabel: formatNumber(root), coeffsRow: [], productsRow: [], bottomRow: [] } };
  }

  const coeffsRow = [...n];
  const productsRow: number[] = [];
  const bottomRow: number[] = [];

  let current = coeffsRow[0];
  bottomRow.push(current);

  for (let i = 1; i < coeffsRow.length; i++) {
    const product = current * root;
    productsRow.push(product);
    current = coeffsRow[i] + product;
    bottomRow.push(current);
  }

  const remainder = bottomRow[bottomRow.length - 1];
  const quotient = bottomRow.slice(0, -1);

  return {
    quotient: normalize(quotient),
    remainder,
    table: {
      rootLabel: formatNumber(root),
      coeffsRow,
      productsRow: [NaN, ...productsRow], // align under columns (first product position empty)
      bottomRow,
    },
  };
}

// ---------------------------------------------------------------------------
// Numeric root refinement (Newton-Raphson) - used when no algebraic closed form
// ---------------------------------------------------------------------------

function refineNewton(coeffs: Coeffs, guess: number, maxIter = 40, tol = 1e-11): number {
  let x = guess;
  const dp = derivative(coeffs);
  for (let i = 0; i < maxIter; i++) {
    const y = evaluate(coeffs, x);
    if (Math.abs(y) < tol) return x;
    const dy = evaluate(dp, x);
    if (Math.abs(dy) < 1e-14) break;
    x = x - y / dy;
    if (!Number.isFinite(x)) break;
  }
  return x;
}

function dedupAndSort(numbers: number[], eps = 1e-7): number[] {
  const sorted = [...numbers].sort((a, b) => a - b);
  const out: number[] = [];
  for (const v of sorted) {
    if (out.length === 0 || Math.abs(out[out.length - 1] - v) > eps) {
      out.push(v);
    }
  }
  return out;
}

/**
 * Find real roots of a polynomial using sign-change bracketing + Newton polishing.
 * Used as a fallback for higher-degree factors that can't be solved by radicals.
 */
export function findRealRootsNumeric(coeffs: Coeffs, rangeMin = -30, rangeMax = 30, steps = 1200): number[] {
  const n = normalize(coeffs);
  if (n.length <= 1) return [];
  if (degree(n) === 0) return [];

  const roots: number[] = [];
  const dx = (rangeMax - rangeMin) / steps;
  let xPrev = rangeMin;
  let yPrev = evaluate(n, xPrev);

  // Check for root exactly at start
  if (Math.abs(yPrev) < 1e-9) roots.push(xPrev);

  for (let i = 1; i <= steps; i++) {
    const x = rangeMin + i * dx;
    const y = evaluate(n, x);

    if (Math.abs(y) < 1e-9) {
      roots.push(x);
    } else if (yPrev * y < 0) {
      // Sign change — isolate and refine
      const mid = (xPrev + x) / 2;
      let refined = refineNewton(n, mid);
      // Also try a few more guesses near the bracket to be robust
      const guesses = [mid, xPrev + dx * 0.2, x - dx * 0.2];
      for (const g of guesses) {
        const r = refineNewton(n, g);
        if (Math.abs(evaluate(n, r)) < 1e-7) {
          refined = r;
          break;
        }
      }
      if (Number.isFinite(refined) && Math.abs(evaluate(n, refined)) < 1e-6) {
        roots.push(refined);
      }
    }
    xPrev = x;
    yPrev = y;
  }

  return dedupAndSort(roots);
}

// ---------------------------------------------------------------------------
// Complete root finding (Rational Root Theorem first, then exact quadratics, then numeric)
// This is the main function used by both Analysis and the Step-by-Step solver.
// ---------------------------------------------------------------------------

export interface RealRoot {
  value: number;
  multiplicity: number;
}

function mergeRootsWithMultiplicity(candidates: RealRoot[]): RealRoot[] {
  if (candidates.length === 0) return [];
  const sorted = [...candidates].sort((a, b) => a.value - b.value);
  const merged: RealRoot[] = [];
  let current = { ...sorted[0] };

  for (let i = 1; i < sorted.length; i++) {
    const next = sorted[i];
    if (Math.abs(current.value - next.value) < 1e-8) {
      current.multiplicity += next.multiplicity;
    } else {
      merged.push(current);
      current = { ...next };
    }
  }
  merged.push(current);
  return merged;
}

/** Find all real roots with multiplicity (prefers exact rationals when possible). */
export function findAllRealRoots(coeffs: Coeffs): RealRoot[] {
  let current = normalize(coeffs);
  const collected: RealRoot[] = [];

  if (current.length === 1 && current[0] === 0) return [{ value: 0, multiplicity: 1 }];

  // --- Phase 1: Rational Root Theorem + repeated synthetic division ---
  const initialCandidates = possibleRationalRoots(current);
  let madeProgress = true;

  while (madeProgress && current.length > 1) {
    madeProgress = false;

    for (const r of initialCandidates) {
      const result = syntheticDivision(current, r);
      if (Math.abs(result.remainder) < 1e-8) {
        // Found exact rational root. Count multiplicity by repeated division.
        let mult = 0;
        let temp = current;
        while (true) {
          const test = syntheticDivision(temp, r);
          if (Math.abs(test.remainder) >= 1e-8) break;
          mult += 1;
          temp = test.quotient;
        }
        collected.push({ value: r, multiplicity: mult });
        current = syntheticDivision(current, r).quotient; // advance by at least one
        madeProgress = true;
        break; // restart candidate scan on reduced poly
      }
    }
  }

  // --- Phase 2: Solve remaining low-degree exactly when possible ---
  const remainingDeg = degree(current);

  if (remainingDeg === 1) {
    // ax + b = 0 => x = -b/a
    const a = current[0];
    const b = current[1];
    const rootVal = -b / a;
    collected.push({ value: rootVal, multiplicity: 1 });
    current = [0];
  } else if (remainingDeg === 2) {
    const [a, b, c] = current;
    const disc = b * b - 4 * a * c;
    if (disc >= -1e-8) {
      const sqrtD = disc < 0 ? 0 : Math.sqrt(disc);
      const r1 = (-b + sqrtD) / (2 * a);
      const r2 = (-b - sqrtD) / (2 * a);
      collected.push({ value: r1, multiplicity: 1 });
      if (Math.abs(r1 - r2) > 1e-9) {
        collected.push({ value: r2, multiplicity: 1 });
      } else {
        // repeated root (should already be caught but safe)
        collected[collected.length - 1].multiplicity = 2;
      }
    }
    current = [0];
  } else if (remainingDeg > 2) {
    // --- Phase 3: Honest numeric approximation for higher degree remainder ---
    const numeric = findRealRootsNumeric(current);
    for (const r of numeric) {
      collected.push({ value: r, multiplicity: 1 }); // multiplicity for irrational roots is hard without factoring
    }
  }

  return mergeRootsWithMultiplicity(collected);
}

// ---------------------------------------------------------------------------
// Turning points via derivative roots + 2nd derivative test
// ---------------------------------------------------------------------------

export interface TurningPoint {
  x: number;
  y: number;
  kind: 'local max' | 'local min' | 'inflection' | 'higher-order';
}

export function findTurningPoints(coeffs: Coeffs): TurningPoint[] {
  const p = normalize(coeffs);
  const p1 = derivative(p);
  const critRoots = findAllRealRoots(p1); // reuse our root finder on p'

  const p2 = derivative(p1);

  return critRoots.map((root) => {
    const x = root.value;
    const y = evaluate(p, x);
    const second = evaluate(p2, x);

    let kind: TurningPoint['kind'] = 'inflection';
    if (Math.abs(second) > 1e-6) {
      kind = second > 0 ? 'local min' : 'local max';
    } else if (root.multiplicity >= 2) {
      kind = 'higher-order';
    }
    return { x, y, kind };
  });
}

// ---------------------------------------------------------------------------
// End behavior (purely determined by degree + sign of leading coefficient)
// ---------------------------------------------------------------------------

export interface EndBehavior {
  description: string;
  left: string;
  right: string;
}

export function getEndBehavior(coeffs: Coeffs): EndBehavior {
  const n = normalize(coeffs);
  const d = degree(n);
  const L = n[0];

  if (d === 0) {
    return {
      description: 'Constant function — horizontal line.',
      left: `p(x) = ${formatNumber(L)}`,
      right: `p(x) = ${formatNumber(L)}`,
    };
  }

  const isEven = d % 2 === 0;
  const leadPositive = L >= 0;
  const signWord = leadPositive ? 'positive' : 'negative';
  const inf = leadPositive ? '+∞' : '-∞';

  if (isEven) {
    return {
      description: `Even degree (${d}) with ${signWord} leading coefficient: both ends head in the same direction.`,
      left: `p(x) → ${inf} as x → -∞`,
      right: `p(x) → ${inf} as x → +∞`,
    };
  } else {
    const leftInf = leadPositive ? '-∞' : '+∞';
    const rightInf = leadPositive ? '+∞' : '-∞';
    return {
      description: `Odd degree (${d}) with ${signWord} leading coefficient: ends go in opposite directions.`,
      left: `p(x) → ${leftInf} as x → -∞`,
      right: `p(x) → ${rightInf} as x → +∞`,
    };
  }
}

// ---------------------------------------------------------------------------
// Full analysis object used by the UI
// ---------------------------------------------------------------------------

export interface PolynomialAnalysis {
  coeffs: Coeffs;
  degree: number;
  leadingCoeff: number;
  expression: string;
  endBehavior: EndBehavior;
  roots: RealRoot[];
  turningPoints: TurningPoint[];
  derivativeCoeffs: Coeffs;
}

export function analyze(coeffsInput: Coeffs | string): PolynomialAnalysis {
  let coeffs: Coeffs;
  if (typeof coeffsInput === 'string') {
    coeffs = parsePolynomial(coeffsInput);
  } else {
    coeffs = normalize(coeffsInput);
  }
  const norm = normalize(coeffs);
  const expr = polyToString(norm);

  return {
    coeffs: norm,
    degree: degree(norm),
    leadingCoeff: norm[0] ?? 0,
    expression: expr,
    endBehavior: getEndBehavior(norm),
    roots: findAllRealRoots(norm),
    turningPoints: findTurningPoints(norm),
    derivativeCoeffs: derivative(norm),
  };
}

// ---------------------------------------------------------------------------
// String parser (supports the examples in the spec)
// ---------------------------------------------------------------------------

/**
 * Parse student-friendly strings into our coeff array (highest first).
 * Supported:
 *   "2x^3 - 5x^2 + 1"
 *   "-x^3 + 2x"
 *   "0.5x^2 - 3"
 *   "x - 7"
 *   "5"
 *   "x^4"
 */
export function parsePolynomial(input: string): Coeffs {
  const raw = (input || '').trim();
  if (!raw) return [0];

  // Normalize
  let s = raw.replace(/\s+/g, '').replace(/\*\*/g, '^');

  // Ensure expression starts with sign so splitting is easy
  if (!s.startsWith('+') && !s.startsWith('-')) {
    s = '+' + s;
  }

  // Split into signed terms: +2x^3  or -5x^2 etc.
  const matches = s.match(/[+-][^+-]+/g) || [];
  if (matches.length === 0) return [0];

  let maxPower = 0;
  const powerToCoeff = new Map<number, number>();

  for (let term of matches) {
    let sign = 1;
    if (term.startsWith('-')) sign = -1;
    let t = term.slice(1); // drop the sign char

    if (!t) continue;

    let coeffStr = '';
    let power = 0;
    const xIndex = t.indexOf('x');

    if (xIndex === -1) {
      // pure constant
      coeffStr = t;
      power = 0;
    } else {
      // has x
      coeffStr = t.slice(0, xIndex);
      const afterX = t.slice(xIndex + 1);

      if (afterX.startsWith('^')) {
        power = parseInt(afterX.slice(1), 10);
      } else if (afterX === '') {
        power = 1; // bare x
      } else {
        power = 1;
      }

      if (coeffStr === '' || coeffStr === '+') coeffStr = '1';
      else if (coeffStr === '-') coeffStr = '-1';
    }

    let coeff = parseFloat(coeffStr);
    if (isNaN(coeff)) coeff = sign; // fallback
    coeff *= sign;

    if (!Number.isFinite(coeff) || !Number.isFinite(power)) continue;

    powerToCoeff.set(power, (powerToCoeff.get(power) || 0) + coeff);
    if (power > maxPower) maxPower = power;
  }

  const result: number[] = [];
  for (let p = maxPower; p >= 0; p--) {
    result.push(powerToCoeff.get(p) || 0);
  }
  return normalize(result);
}

// ---------------------------------------------------------------------------
// STEP-BY-STEP EDUCATIONAL SOLVER (the "Critical Feature")
// ---------------------------------------------------------------------------

export type StepKind =
  | 'rrt-candidates'
  | 'synthetic'
  | 'factor-extracted'
  | 'quadratic-complete-square'
  | 'linear'
  | 'numeric'
  | 'note';

export interface SolverStep {
  kind: StepKind;
  title: string;
  explanation: string;
  // For synthetic division display
  synthetic?: {
    root: number;
    rootStr: string;
    coeffsRow: number[];
    productsRow: number[];
    bottomRow: number[];
    remainder: number;
    quotientStr: string;
  };
  // For completing the square
  completeSquare?: string[];
  // Final roots contributed at this step
  rootsFound?: RealRoot[];
}

export interface StepByStepSolution {
  original: string;
  steps: SolverStep[];
  allRoots: RealRoot[];
  factoredForm: string;
  hasExactSolution: boolean;
  note?: string;
}

/**
 * The heart of the learning tool.
 * Produces a sequence of steps a student can follow by hand:
 *   1. List candidates via Rational Root Theorem
 *   2. Show every synthetic division attempt that succeeds (with full table)
 *   3. When a quadratic remains → walk through Completing the Square
 *   4. For degree >=3 irreducible remainder → numeric + Abel-Ruffini honesty note
 */
export function factorAndSolveWithSteps(input: Coeffs | string): StepByStepSolution {
  const analysis = analyze(input);
  let current = [...analysis.coeffs];
  const originalStr = analysis.expression;
  const steps: SolverStep[] = [];
  const allRoots: RealRoot[] = [];

  if (degree(current) === 0) {
    return {
      original: originalStr,
      steps: [{ kind: 'note', title: 'Constant', explanation: 'A constant has no roots.', rootsFound: [] }],
      allRoots: [],
      factoredForm: originalStr,
      hasExactSolution: true,
    };
  }

  // Step 0: Rational Root Theorem candidates
  const candidates = possibleRationalRoots(current);
  steps.push({
    kind: 'rrt-candidates',
    title: 'Rational Root Theorem — Possible Rational Roots',
    explanation:
      'Any rational root p/q (in lowest terms) must have p dividing the constant term and q dividing the leading coefficient. ' +
      'We only need to test these candidates.',
    rootsFound: [],
  });

  // Phase 1 & 2: Extract rational roots using synthetic division
  let progress = true;
  while (progress && current.length > 1) {
    progress = false;

    for (const r of candidates) {
      const syn = syntheticDivision(current, r);
      if (Math.abs(syn.remainder) > 1e-8) continue;

      // Success — show the division table
      const rootStr = formatNumber(r);
      const quotStr = polyToString(syn.quotient);

      steps.push({
        kind: 'synthetic',
        title: `Synthetic Division by (x − ${rootStr})`,
        explanation: `Remainder = 0, therefore (x − ${rootStr}) is an exact factor. The bottom row gives the coefficients of the quotient.`,
        synthetic: {
          root: r,
          rootStr,
          coeffsRow: syn.table.coeffsRow,
          productsRow: syn.table.productsRow,
          bottomRow: syn.table.bottomRow,
          remainder: syn.remainder,
          quotientStr: quotStr,
        },
        rootsFound: [],
      });

      // Count multiplicity
      let mult = 0;
      let tempPoly = current;
      while (true) {
        const test = syntheticDivision(tempPoly, r);
        if (Math.abs(test.remainder) >= 1e-8) break;
        mult++;
        tempPoly = test.quotient;
      }

      const rootObj: RealRoot = { value: r, multiplicity: mult };
      allRoots.push(rootObj);

      // Record a clean "factored out" step
      const factorStr = mult > 1 ? `(x − ${rootStr})^${mult}` : `(x − ${rootStr})`;
      steps.push({
        kind: 'factor-extracted',
        title: `Factor Extracted: ${factorStr}`,
        explanation: `We divided out the factor ${mult} time(s). Quotient is now ${quotStr}.`,
        rootsFound: [rootObj],
      });

      current = tempPoly; // reduced
      progress = true;
      break;
    }
  }

  // Phase: remaining polynomial
  const remDeg = degree(current);

  if (remDeg === 1) {
    const a = current[0];
    const b = current[1];
    const rootVal = -b / a;
    const rootObj: RealRoot = { value: rootVal, multiplicity: 1 };
    allRoots.push(rootObj);

    steps.push({
      kind: 'linear',
      title: 'Solve Remaining Linear Factor',
      explanation: `${polyToString(current)} = 0  ⇒  x = ${formatNumber(rootVal)}`,
      rootsFound: [rootObj],
    });
  } else if (remDeg === 2) {
    // ------------------------------------------------------------------
    // COMPLETING THE SQUARE — PURE DETERMINISTIC CLASSICAL ALGEBRA
    // The strings below are generated by ordinary procedural code that
    // replicates the EXACT sequence of manual algebraic manipulations
    // a student performs on paper. There is no AI, no LLM, no symbolic
    // computer algebra system, and no external service involved.
    // Every transformation (divide by a, complete the square, take ±sqrt)
    // is simple arithmetic + string formatting.
    // ------------------------------------------------------------------
    const [a, b, c] = current;
    const completeSteps: string[] = [];

    completeSteps.push(`We have the quadratic factor: ${polyToString(current)} = 0`);
    completeSteps.push(`Divide every term by a = ${formatNumber(a)}:`);

    const bNorm = b / a;
    const cNorm = c / a;
    completeSteps.push(`x² + ${formatNumber(bNorm)}x + ${formatNumber(cNorm)} = 0`);

    completeSteps.push(`Move the constant term to the right side:`);
    completeSteps.push(`x² + ${formatNumber(bNorm)}x = ${formatNumber(-cNorm)}`);

    const halfB = bNorm / 2;
    const halfBSquared = halfB * halfB;
    completeSteps.push(`Take half the coefficient of x (${formatNumber(bNorm)} / 2 = ${formatNumber(halfB)}), then square it: ${formatNumber(halfBSquared)}`);

    completeSteps.push(`Add ${formatNumber(halfBSquared)} to both sides:`);
    const right = -cNorm + halfBSquared;
    completeSteps.push(`x² + ${formatNumber(bNorm)}x + ${formatNumber(halfBSquared)} = ${formatNumber(right)}`);

    completeSteps.push(`Left side is a perfect square:`);
    completeSteps.push(`(x + ${formatNumber(halfB)})² = ${formatNumber(right)}`);

    const sqrtRight = Math.sqrt(Math.max(0, right));
    completeSteps.push(`Take square root of both sides:`);
    completeSteps.push(`x + ${formatNumber(halfB)} = ±${formatNumber(sqrtRight)}`);

    const r1 = -halfB + sqrtRight;
    const r2 = -halfB - sqrtRight;

    completeSteps.push(`Solve for x:`);
    completeSteps.push(`x = ${formatNumber(r1)}   or   x = ${formatNumber(r2)}`);

    const rootsHere: RealRoot[] = [
      { value: r1, multiplicity: Math.abs(r1 - r2) < 1e-8 ? 2 : 1 },
    ];
    if (Math.abs(r1 - r2) >= 1e-8) {
      rootsHere.push({ value: r2, multiplicity: 1 });
    }

    allRoots.push(...rootsHere);

    steps.push({
      kind: 'quadratic-complete-square',
      title: 'Solve Quadratic by Completing the Square',
      explanation: 'Completing the square always works and shows the geometry behind the quadratic formula.',
      completeSquare: completeSteps,
      rootsFound: rootsHere,
    });
  } else if (remDeg >= 3) {
    // Higher degree remaining — numeric + honest note
    const numericRoots = findRealRootsNumeric(current);
    const rootsHere = numericRoots.map((v) => ({ value: v, multiplicity: 1 }));

    // Try to detect obvious repeated numeric roots (rare)
    const mergedHere = mergeRootsWithMultiplicity(rootsHere);
    allRoots.push(...mergedHere);

    steps.push({
      kind: 'numeric',
      title: `Remaining Degree-${remDeg} Factor — Numerical Approximation`,
      explanation:
        `The remaining factor ${polyToString(current)} has degree ${remDeg}. ` +
        'We locate real roots by sampling for sign changes and refining with Newton-Raphson iteration.',
      rootsFound: mergedHere,
    });

    steps.push({
      kind: 'note',
      title: 'Important Mathematical Note',
      explanation:
        'Polynomials of degree 5 or higher have no general solution in radicals (Abel–Ruffini theorem). ' +
        'Even for some degree 3 and 4 cases the exact radical form is extremely complicated. ' +
        'Numerical methods give excellent practical approximations for real-world use and graphing.',
    });
  }

  // Build nice factored form string from collected roots
  const factoredTerms = allRoots
    .sort((a, b) => a.value - b.value)
    .map((r) => {
      const v = formatNumber(r.value);
      return r.multiplicity > 1 ? `(x − ${v})^${r.multiplicity}` : `(x − ${v})`;
    });

  let factoredForm = factoredTerms.length > 0 ? factoredTerms.join('') : polyToString(current);
  if (analysis.leadingCoeff !== 1 && analysis.leadingCoeff !== 0) {
    factoredForm = `${formatNumber(analysis.leadingCoeff)} · ${factoredForm}`;
  }

  const hasExact = !steps.some((s) => s.kind === 'numeric');

  return {
    original: originalStr,
    steps,
    allRoots: mergeRootsWithMultiplicity(allRoots),
    factoredForm,
    hasExactSolution: hasExact,
    note: hasExact ? undefined : 'Some roots are numeric approximations only.',
  };
}

// ---------------------------------------------------------------------------
// Convenience: generate nice sample points for Chart.js
// ---------------------------------------------------------------------------

export interface Point {
  x: number;
  y: number;
}

/**
 * Generate smooth points for plotting over an interval.
 * Uses enough points for Chart.js to look like a continuous curve.
 */
export function samplePolynomial(coeffs: Coeffs, xMin: number, xMax: number, numPoints = 280): Point[] {
  const n = normalize(coeffs);
  const pts: Point[] = [];
  if (xMax <= xMin) return pts;
  const step = (xMax - xMin) / (numPoints - 1);
  for (let i = 0; i < numPoints; i++) {
    const x = xMin + i * step;
    pts.push({ x, y: evaluate(n, x) });
  }
  return pts;
}

/**
 * Suggest a sensible plotting window based on roots + turning points.
 * Keeps the graph focused on the interesting region while always showing a bit of end behavior.
 */
export function suggestViewWindow(analysis: PolynomialAnalysis): { min: number; max: number } {
  const xs: number[] = [ -4, 4 ];
  for (const r of analysis.roots) xs.push(r.value);
  for (const t of analysis.turningPoints) xs.push(t.x);

  let minX = Math.min(...xs);
  let maxX = Math.max(...xs);

  // Add padding (at least 15% on each side or 1 unit)
  const spread = maxX - minX;
  const pad = Math.max(1.2, spread * 0.18);
  minX -= pad;
  maxX += pad;

  // Never too narrow for high degree or large leading
  if (maxX - minX < 3) {
    minX -= 1.5;
    maxX += 1.5;
  }
  return { min: Math.round(minX * 10) / 10, max: Math.round(maxX * 10) / 10 };
}
